### PR TITLE
Fix Mouse zooming overlay

### LINKED ISSUE #145: Mouse zooming doesn't show overlay when scrolled down
Kapture 2021-07-08 at 14 24 45

### PR DESCRIPTION
**Pull request by muddana-satish**
fixes #145

Signed-off-by: muddana-satish <satish.muddana@ericsson.com>

### CODE REVIEW

**Review by MatthewKhouzam — APPROVED** [review]
lgtm

File: timeline-chart/src/layer/time-graph-chart.ts [hunk 1]
```diff
@@ -346,7 +346,7 @@ export class TimeGraphChart extends TimeGraphChartLayer {
                 opacity: 0.2,
                 position: {
                     x: mouseStartX,
-                    y: 0
+                    y: this.rowController.verticalOffset
```
Comment (PatrickTasse) [inline timeline-chart/src/layer/time-graph-chart.ts:349]: If you mouse-wheel up/down while right-click zooming, you can see a gap on top of original vertical offset.

I believe the proper fix is to change height to :

Math.max(this.stateController.canvasDisplayHeight, this.rowController.totalHeight)

**Review by PatrickTasse — CHANGES_REQUESTED** [review]

File: timeline-chart/src/layer/time-graph-chart.ts (hunk 1 above)
Comment (muddana-satish) [reply timeline-chart/src/layer/time-graph-chart.ts]: Updated. Thanks.

**Review by PatrickTasse — APPROVED** [review]
