### PR TITLE
Reset fetching flag in a try-finally statement

### LINKED ISSUE #66: Uncaught exception causes prevents further query to server to happen
The flag "this.fetching" can be set to true and won't be reset if an exception created in between (see lines below in time-graph-chart.ts).

BR
Bernd

           `this.fetching = true;
            const rowData = await this.providers.dataProvider(viewRange, resolution);
            if (rowData) {
                this.providedResolution = rowData.resolution;
                this.providedRange = rowData.range;
                this.setRowModel(rowData.rows);
                this.removeChildren();
                this.addRows(this.rows, this.rowController.rowHeight);
            }
            this.fetching = false;`

### PR DESCRIPTION
**Pull request by bhufmann**
Fixes #66

Signed-off-by: Bernd Hufmann <Bernd.Hufmann@ericsson.com>

### CODE REVIEW

File: timeline-chart/src/layer/time-graph-chart.ts [hunk 1]
```diff
@@ -219,18 +219,21 @@ export class TimeGraphChart extends TimeGraphChartLayer {
...
+                    this.providedResolution = rowData.resolution;
+                    this.providedRange = rowData.range;
+                    this.setRowModel(rowData.rows);
+                    this.removeChildren();
+                    this.addRows(this.rows, this.rowController.rowHeight);
+                    if (this.isNavigating) {
+                        this.selectStateInNavigation();
+                    }
                 }
+            } catch (error) {
```
Comment (bhufmann) [inline timeline-chart/src/layer/time-graph-chart.ts:234]: should be finally :-)

**Review by PatrickTasse — APPROVED** [review]

File: timeline-chart/src/layer/time-graph-chart.ts [hunk 2]
```diff
@@ -219,18 +219,21 @@ export class TimeGraphChart extends TimeGraphChartLayer {
...
+                    this.providedRange = rowData.range;
+                    this.setRowModel(rowData.rows);
+                    this.removeChildren();
+                    this.addRows(this.rows, this.rowController.rowHeight);
+                    if (this.isNavigating) {
+                        this.selectStateInNavigation();
+                    }
                 }
+            } finally {
+                this.fetching = false;
```
Comment (muddana-satish) [inline timeline-chart/src/layer/time-graph-chart.ts:235]: though not related, can we also set this.isNavigating to 'false' to make sure we set all the flags correctly.

Comment (bhufmann) [reply timeline-chart/src/layer/time-graph-chart.ts:235]: make sense
