### PR TITLE
Resize background as well when resizing canvas.

### LINKED ISSUE #99: Background of chart not resized when resizing the window
When resizing the TimeGraphContainer using method reInitCanvasSize(newWidth, newHeight), all the layers are updated but not the background layer. This leads to incorrect visualizations of the data in the new added screen area. 

See https://github.com/theia-ide/theia-trace-extension/issues/209#issue-782150707 for more details on it.

### PR DESCRIPTION
**Pull request by bhufmann**
Fixes #99

Signed-off-by: Bernd Hufmann <Bernd.Hufmann@ericsson.com>

### CODE REVIEW

**Review by MatthewKhouzam — APPROVED** [review]
Makes great sense! Also works! Thanks Bernd!

File: timeline-chart/src/time-graph-container.ts [hunk 1]
```diff
@@ -81,10 +83,15 @@ export class TimeGraphContainer {
...
         if (newHeight === undefined) {
             newHeight = this.config.height;
+        } else {
+            this.config.height = newHeight;
         }
+
         this.application.renderer.resize(newWidth, newHeight);
         this.stateController.updateDisplayWidth();
         this.stateController.updateDisplayHeight();
+        this.background.displayObject.height = newHeight;
```
Comment (bhufmann) [inline timeline-chart/src/time-graph-container.ts:93]: the width has to be updated as well.

Comment (bhufmann) [reply timeline-chart/src/time-graph-container.ts:93]: I'll update that patch for that.
